core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login/', include('perfil.urls')),
    path('examen/', include('examen.urls', namespace='examen')),
]

examen/urls.py
from django.urls import path
from . import views


app_name = 'examen'

urlpatterns = [
    path('consulta/', views.consulta, name='consulta'),
    path('aplicacion/', views.aplicacion, name='aplicacion'),
]

examen/models.py
from django.db import models
from perfil.models import CustomUser


class Examen(models.Model):
    nombre = models.CharField(max_length=50, verbose_name="Nombre del examen")  
    calificacion_minima = models.FloatField(verbose_name="Calificación mínima")
    activo = models.BooleanField(verbose_name="¿Activo?")
    observaciones = models.TextField(verbose_name="Observaciones")

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name = "Examen"
        verbose_name_plural = "Exámenes"
        ordering = ["nombre"]


class Pregunta(models.Model):
    enunciado = models.TextField(verbose_name="Enunciado de la pregunta")
    examen = models.ForeignKey(Examen, on_delete=models.CASCADE, verbose_name="Examen", related_name="preguntas")

    def __str__(self):
        return self.enunciado
    
    class Meta:
        verbose_name = "Pregunta"
        verbose_name_plural = "Preguntas"
        ordering = ["enunciado"]


class Respuesta(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE, verbose_name="Pregunta", related_name="respuestas")
    respuesta = models.TextField(verbose_name="Respuesta")
    es_correcta = models.BooleanField(verbose_name="¿Es correcta?")

    def __str__(self):
        return self.respuesta
    
    class Meta:
        verbose_name = "Respuesta"
        verbose_name_plural = "Respuestas"
        ordering = ["respuesta"]


class Resultado(models.Model):
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Usuario", related_name="resultados")
    examen = models.ForeignKey(Examen, on_delete=models.CASCADE, verbose_name="Examen", related_name="resultados")
    calificacion = models.FloatField(verbose_name="Calificación")
    fecha_aplicacion = models.DateField(verbose_name="Fecha de aplicación")
    hora_inicio = models.TimeField(verbose_name="Hora de inicio", null=True, blank=True)
    hora_fin = models.TimeField(verbose_name="Hora de fin", null=True, blank=True)

    def __str__(self):
        return str(self.examen)
    
    class Meta:
        verbose_name = "Resultado"
        verbose_name_plural = "Resultados"
        ordering = ["calificacion"]


class RespuestaUsuario(models.Model):
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Usuario", related_name="respuestas")
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE, verbose_name="Pregunta", related_name="respuestas_usuario")
    respuesta_usuario = models.ForeignKey(Respuesta, on_delete=models.CASCADE, verbose_name="Respuesta", related_name="respuestas_usuario")
    respuesta_correcta = models.BooleanField(verbose_name="¿Es correcta?", default=False)

    def __str__(self):
        return str(self.respuesta_usuario)
    
    class Meta:
        verbose_name = "Respuesta del agente"
        verbose_name_plural = "Respuestas del agente"
        ordering = ["respuesta_usuario"]

examen/views.py
from django.shortcuts import render
from examen.models import Examen, Pregunta, Respuesta


def consulta(request):
    examen_activo = Examen.objects.filter(activo=True).first()
    examen = examen_activo.nombre if examen_activo else None
    contexto = {
        'examen': examen,
    }
    return render(request, 'examen/consulta_examen.html', contexto)


def aplicacion(request):
    examen_activo = Examen.objects.filter(activo=True).first()
    examen = examen_activo.nombre if examen_activo else None
    preguntas = Pregunta.objects.filter(examen=examen_activo) if examen_activo else []
    respuestas = Respuesta.objects.filter(pregunta__in=preguntas) if preguntas else []
    contexto = {
        'examen': examen,
        'preguntas': preguntas,
        'respuestas': respuestas,
    }
    return render(request, 'examen/aplicacion.html', contexto)

examen/templates/examen/aplicacion.html
{% extends "base.html" %}


{% block content %}

    <div class="container col-8 mt-4">
        <h3 class="mb-4">Aplicación del examen: {{examen}}</h3>
        <form action="#" method='POST'>
            {% csrf_token %}
            {% for pregunta in preguntas %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title mb-3">{{pregunta}}</h5>
                        {% for respuesta in pregunta.respuestas.all %}
                        <div class="form-group mt-2">
                            <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" id="opcion{{respuesta.id}}" name="respuesta{{pregunta.id}}" value="{{respuesta.id}}">
                            <label class="form-check-label" for="opcion3">{{ respuesta.respuesta }}</label>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Enviar respuestas</button>
        </form>
    </div>

{% endblock %}

examen/templates/examen/consulta_examen.html
{% extends 'base.html' %}


{% block content %}
    <div class="container mt-5">
        {% if examen %}
            <div class="container col-7">
                <div class="card text-center bg-light">
                    <div class="card-header p-3"></div>
                    <div class="card-body">
                        <h5 class="card-title">Exámen disponible</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur consequuntur ullam alias doloribus velit? Molestiae nostrum ea dignissimos asperiores quasi?.</p>
                        <a href="{% url 'examen:aplicacion' %}" class="btn btn-success">Iniciar</a>
                    </div>
                    <div class="card-footer text-muted p-3"></div>
                    </div>
            </div>
        {% else %}
            <div class="container col-7">
                <div class="card text-center bg-light">
                    <div class="card-header p-3"></div>
                    <div class="card-body">
                      <h5 class="card-title">Exámen no disponible</h5>
                      <p class="card-text">Por el momento no se ha cargado ningún exámen al que aplicar. Intente más tarde.</p>
                      <a href="{% url 'home' %}" class="btn btn-danger">Regresar</a>
                    </div>
                    <div class="card-footer text-muted p-3"></div>
                  </div>
            </div>
        {% endif %}

        

    </div>
{% endblock %}