core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login/', include('perfil.urls')),
    path('examen/', include('examen.urls', namespace='examen')),
]

perfil/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', LoginView.as_view(template_name='perfil/login.html'), name='login'),
    path('registro/', views.registro, name='registro'),
    path('logout/', views.logout_view, name='logout'),
]

perfil/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Supervisor(models.Model):
    nombre = models.CharField(max_length=50, verbose_name="Nombre del supervisor")
    apellido_paterno = models.CharField(max_length=50, verbose_name="Apellido paterno del supervisor")
    apellido_materno = models.CharField(max_length=50, verbose_name="Apellido materno del supervisor")

    def __str__(self):
        return self.nombre + " " + self.apellido_paterno + " " + self.apellido_materno
    
    class Meta:
        verbose_name = "Supervisor"
        verbose_name_plural = "Supervisores"
        ordering = ["nombre"]


class CustomUser(AbstractUser):
    nombres = models.CharField(max_length=50)
    apellido_paterno = models.CharField(max_length=50)
    apellido_materno = models.CharField(max_length=50)
    numero_nomina = models.IntegerField(primary_key=True, verbose_name="Número de nómina")
    email = models.EmailField(unique=True)
    supervisor = models.ForeignKey(Supervisor, on_delete=models.CASCADE, verbose_name="Supervisor", blank=True, null=True)

    def __str__(self):
        return self.nombres + " " + self.apellido_paterno + " " + self.apellido_materno
    
    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"
        ordering = ["numero_nomina"]

perfil/forms.py
"""
Para modificar el formulario de login de Django y hacer que solicite el número de nómina en lugar del nombre de usuario, debes crear un formulario personalizado que herede de AuthenticationForm, la cual es la clase que representa el formulario de inicio de sesión predeterminado en Django.

Para hacer esto, debes crear un archivo forms.py 
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.forms.widgets import CheckboxInput  
from django.forms.widgets import TextInput


class CustomLoginForm(AuthenticationForm):
    username = forms.IntegerField(label="Usuario")

    error_messages = {
        'invalid_login': "Por favor, ingrese un número de nómina y contraseña correctos."
    }

   
   
class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        # agrega campos personalizados al formulario
        fields = UserCreationForm.Meta.fields + ('nombres','apellido_paterno','apellido_materno','numero_nomina','email','supervisor','is_staff', 'is_superuser')

    # agregar clases de bootstrap a los campos del formulario
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            # elimina las etiquetas de los campos
            self.fields[field].label = ''

        # Agregar clases CSS a los campos del formulario
        self.fields['username'].widget.attrs.update({'placeholder': 'Usuario'})
        self.fields['nombres'].widget.attrs.update({'placeholder': 'Nombre(s)'})
        self.fields['apellido_paterno'].widget.attrs.update({'placeholder': 'Apellido Paterno'})
        self.fields['apellido_materno'].widget.attrs.update({'placeholder': 'Apellido Materno'})
        self.fields['numero_nomina'].widget.attrs.update({'placeholder': 'Número de Nómina'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Correo Electrónico'})
        self.fields['supervisor'].widget.attrs.update({'placeholder': 'Supervisor'})
        self.fields['password1'].widget.attrs.update({'placeholder': 'Contraseña'})
        self.fields['password2'].widget.attrs.update({'placeholder': 'Confirmar Contraseña'})
        self.fields['is_staff'].widget = CheckboxInput(attrs={'class': 'form-check-input'})
        self.fields['is_superuser'].widget = CheckboxInput(attrs={'class': 'form-check-input'})

perfil/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import CustomLoginForm
from .forms import CustomUserCreationForm
from django.contrib import messages


def login(request):
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = CustomLoginForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(request, username=username, password=password)
            if user is not None:
                # login user and redirect to home page
                login(request, user)
                return redirect('home')
            # redirect to a new URL:
        return render(request, "login.html", {"form": form})
    
        

    # if a GET (or any other method) we'll create a blank form
    else:
        form = CustomLoginForm()
        return render(request, "perfil/login.html", {"form": form})
    

def registro(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '¡Tu cuenta ha sido creada exitosamente! Por favor, inicia sesión para continuar.')
            return redirect('perfil:login')
    else:
        form = CustomUserCreationForm()
        if form.errors:
            messages.success(request, 'Algo salió mal. Por favor, intente de nuevo.')
    return render(request, 'perfil/registro.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')


   

perfil/templates/perfil/login.html
{% extends 'base.html' %}
{% load custom_tags %}
{% load widget_tweaks %}


{% block content %}

    <!-- Muestra mensaje de error si lo hay -->
    {% if form.errors %}
    <div class="container-fluid alert alert-danger alert-dismissible fade show" role="alert">
        <strong>¡Error!</strong> Por favor, comprueba los datos introducidos.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    <!-- ---------------------------------- -->

  <div class="container mb-3 col-sm-6 col-md-3">
  </br>
      <h2>Iniciar sesión</h2>
      {{error}}

      <form method="post" action="{% url 'perfil:login' %}" class="form-group">
        {% csrf_token %}

        <div class="mb-3">
            <!-- <label for="{{ form.username.id_for_label }}" class="form-label">Usuario</label> -->
            {{ form.username|add_class:"form-control"|attr:"placeholder:Usuario"|attr:"autofocus:false" }}
        </div>

        <div class="mb-3">
            <!-- <label for="{{ form.password.id_for_label }}" class="form-label">Contraseña</label> -->
            {{ form.password|add_class:"form-control"|attr:"placeholder:Contraseña"}}
        </div>

        <button type="submit" class="btn btn-primary col-4">Enviar</button>
      </form>

      <div class="mt-4">
        <p>¿No tienes cuenta? <a href="{% url 'perfil:registro' %}">Regístrate</a></p>
      </div>
  </div>


  
{% endblock %}

perfil/templates/perfil/registro.html
{% extends 'base.html' %}
{% load custom_tags %}
{% load widget_tweaks %}



{% block content %}

    <!-- Si hay errores en el formulario, se muestran -->
        {% if form.errors %}
         <div class="container-fluid alert alert-warning alert-dismissible fade show" role="alert">
           Tus datos tienen errores. Por favor, corrígelos e inténtalo de nuevo.
           {% for field in form %}
               {% if field.errors %}
                   {{ field.errors }}
               {% endif %}
           {% endfor %}
           <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
         </div>
        {% endif %}
    <!-- ---------------------------------- -->

    <div class="container mt-3 mb-5 col-md-7">
        <h1 class="mb-4">Registro de usuario</h1>
        <form method="post" action="{% url 'perfil:registro' %}" class="form-group">
        {% csrf_token %}   
        {{form.as_p}} 
        <button type="submit" class="btn btn-primary">Registrarse</button>
        <button class="btn btn-danger"><a href="{% url 'home' %}" class="text-decoration-none text-light">Cancelar</a></button>
        </form>
    </div>

    

{% endblock %}