core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login/', include('perfil.urls')),
    path('examen/', include('examen.urls', namespace='examen')),
]

examen/urls.py
from django.urls import path
from . import views


app_name = 'examen'

urlpatterns = [
    path('consulta/', views.consulta, name='consulta'),
    path('aplicacion/', views.aplicacion, name='aplicacion'),
]

perfil/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', LoginView.as_view(template_name='perfil/login.html'), name='login'),
    path('registro/', views.registro, name='registro'),
    path('logout/', views.logout_view, name='logout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- TITULO -->
    <title>{% block title %}{% endblock %}</title>
    <!-- LINK BOOTSTRAP -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
    
    {% include 'navbar.html' %}

    <!-- MENSAJES DE ERROR -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}


    {% block content %}{% endblock %}


    <!-- SCRIPTS -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Informer</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#">Avisos</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Examen
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'examen:consulta' %}">Consulta</a></li>
                <li><a class="dropdown-item" href="#">Histórico</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
            </li>
          {% endif %}
        </ul>   
        <ul class="navbar-nav ms-auto">

            {% if user.is_authenticated %}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                ¡Bienvenido, {{user.nombres}} {{user.apellido_paterno}}!
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Editar perfil</a></li>
                  {% if user.is_staff %}
                      <li>
                          <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Site</a>
                      </li>
                  {% endif %}
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'perfil:logout' %}">Cerrar sesión</a></li>
                </ul>
              </li>
              
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:login' %}">Iniciar sesión</a>
              </li>
            {% endif %}
        </ul>
      </div>
    </div>
  </nav>